// <auto-generated />
using HiddenGarden.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiddenGarden.Migrations
{
    [DbContext(typeof(HiddenGardenContext))]
    [Migration("20230404163724_UpdateHiddenGardenContext")]
    partial class UpdateHiddenGardenContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HiddenGarden.Models.Backyard", b =>
                {
                    b.Property<int>("BackyardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Instructions")
                        .HasColumnType("longtext");

                    b.Property<float>("Latitude")
                        .HasColumnType("float");

                    b.Property<float>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Service")
                        .HasColumnType("longtext");

                    b.HasKey("BackyardId");

                    b.ToTable("Backyards");

                    b.HasData(
                        new
                        {
                            BackyardId = 1,
                            Address = "13704 SE Salmon St, Portland OR, 97233",
                            Description = "Free fig tree fruit",
                            Instructions = "Pay $5, follow road signs",
                            Latitude = 0f,
                            Longitude = 0f,
                            Service = "Fig trees"
                        },
                        new
                        {
                            BackyardId = 2,
                            Address = "Bennelong Point, Sydney NSW 2000, Australia",
                            Description = "Free Apples",
                            Instructions = "Ask the receptionist for apples!",
                            Latitude = 0f,
                            Longitude = 0f,
                            Service = "Apple Trees"
                        },
                        new
                        {
                            BackyardId = 3,
                            Address = "Pierre’s Bakery, Portland, OR",
                            Description = "Day after baked goods",
                            Instructions = "Come up to the window and ask for knock!",
                            Latitude = 0f,
                            Longitude = 0f,
                            Service = "Bread and Pastries"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
